//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phongkham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENHNHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENHNHAN()
        {
            this.DONTHUOCs = new HashSet<DONTHUOC>();
            this.HOADONs = new HashSet<HOADON>();
            this.HOSOBENHANs = new HashSet<HOSOBENHAN>();
            this.LICHKHAMs = new HashSet<LICHKHAM>();
            this.XETNGHIEMs = new HashSet<XETNGHIEM>();
        }
    
        public int NamSinh { get; set; }
        public string TenBN { get; set; }
        public int MaBN { get; set; }
        public bool GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string Phone { get; set; }
        public string CCCD { get; set; }
        public string TenKhoa { get; set; }
        public string MaBH { get; set; }
        public string PasswordBN { get; set; }
        public string Role { get; set; }
    
        public virtual BAOHIEM BAOHIEM { get; set; }
        public virtual KHOA KHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONTHUOC> DONTHUOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSOBENHAN> HOSOBENHANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHKHAM> LICHKHAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XETNGHIEM> XETNGHIEMs { get; set; }
    }
}
