//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phongkham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MaHD { get; set; }
        public int TongTra { get; set; }
        public System.DateTime NGAY { get; set; }
        public int MaBN { get; set; }
        public Nullable<int> IDKham { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
        public virtual LICHKHAM LICHKHAM { get; set; }
    }
}
